name: paren
description: "A new Flutter project."
publish_to: "none"
version: 1.9.20+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  get: 4.7.3
  dio: 5.9.0
  shared_preferences: 2.5.3
  url_launcher: 6.3.2
  share_plus: 12.0.1
  fl_chart: 1.1.1
  home_widget: 0.8.1
  flutter_colorpicker: 1.1.0
  stupid_simple_sheet: 0.6.2+3
  # image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/back.png"
  adaptive_icon_foreground: "assets/icon/fore.png"
  adaptive_icon_monochrome: "assets/icon/mono.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
